language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  on:
    all_branches: true
  app: cookbook13
  api_key:
    secure: "A+h1sRJqtqTT3NENMjc3TLTNDS8MrU+G9HwfrC3IY0JuW4uZLM19uWuDbvRAZ5m4GiavwA2nvNDBFovsv4h4t5I83VZAjI9vkUnBWTMJRbdNdtD/oYwN6zE03NNyLXSH9HV7eoKIbqwcnphw7Xy4rOnzqD1f7xD7JD4E6KRSmE5ntdIamlaPzwToiJwwLOBM7sCjN4JkJ+Jxhh9We6NezhDotL6ALU1Qyy8uCFo0d1ssAi2jw513L2fSxeL+yJZ5nNFbbDi7ct4SIS+jZinubSe2tIyBFo9sOT1Lw3zSSeD9rru+EUdMo3DCY46Nk2gg8dCySdpbtp1Rv0WeBxivM3DAHGKWlZuOA0ylmamcoTnZmT5PBKS0mRRPdQyekqfKI03AkIb2UVXOlvJbJbR/VmK10J+MtlO1QkezdnsHB4t09H0KuF2CgL7sATem7Dmwp09zTYG9dxFD0MmmA//4WRNQAydXNsh2u4iCepAkRqQa3bz6pXDl1LvImPRRoBoQQYNoyuGbFKdFFOJDdiOaTVto9OdSpkvkoOdu18rf287YrqFqFQrs9Hbk4I62/BrCnVnWXCOOh02RmAHkcUdn8RpI3oaOZLcQuwarj2f3zbhzSuPbicPwhD2yNOKty9J+WPH/Sid5epBhksx44yQdErcMysCzzVXrOVPWrt7uzDY="
