language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn run build
deploy:
  provider: heroku
  api_key: ...
  on: production
  app: cookbook13
on:
  branch: master