language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  on:
    all_branches: true
  app: cookbook13
  api_key:
    secure: Q70TDpavgjPnOAKuamr681zQ6T1cDzwYU0e0FaqDAfikqXw4R3kZMfXn//0AajkvQgcX70H+30C57ayWUV7EZX2vtgNRVIwOAwRmR/+laJ6Vbw/Du2oVMzKKz7C/UBQGmDPPLSq1RhKH6pq6LaIPGBviJarJjOo/tJIG+YIdCVMeNNuE/P3gvvM76IGNU5JNw6UUo18aRheypfefss6oAdmMoT/cqeCYLrJ9IecVaZA4/PJhznwO7haCXKujlqlWLSUazd3QkqXo1PCcv1yLNp9ZZsUWLP3b6AWRapUOPG7mEIGmrMNhXMgn1NAvv+VhTOHydAZUWj6SbVZ4KjRoBCctevf50Z5LUiMpw5Xn2Cxb20v5wDWV3bwx5jxxbs6GnlWbME2pRllRSHdwt+xdCjHGTybpANkCsoa0zLyIoQnZ/bZP+tZIUNvAT5peOqatzV+L0hIhlJ/dnWL5dvDULvii02Dc6aMp3g0q6wEVlsxppYiRfvPgoZWoXqESpAn223eW+zKaarKSJE82sT71pqPhr3TXIyk1XlM1r5tKDmSKsfZuJpLv0fX4UTZSEEdLWfu45sJ21Rm1ZPGZj5AjikWcbt8LgRuSMwOqexSYBiMaDmoVau5Kjls5Kcj/ae9giqKxUdnKyiyhh6JuJAsunOQwTDOqvjggHzOrkX+nbO0=

